### ISSUE TITLE
Cannot login with Google.

### ISSUE THREAD

**Issue by justinjeanpierre** [justinjeanpierre/simon#15]
When I run the app and try to "Sign in with Google", I am redirected to [this error page](https://accounts.google.com/o/oauth2/auth?response_type=code&client_id=435957539193-vr1rgnqb7laiucm4h5r53h990741cq4p.apps.googleusercontent.com&redirect_uri=http%3A%2F%2Flocalhost%3A5000%2Fgoogle%2Fauthorized&scope=email) instead of seeing the confirmation popup.

Steps to reproduce:
- start the app
- go to the login page (http://localhost:5000/login/)
- click the "Sign in with Google" button.
- see error page.

I was expecting to see a popup asking me to confirm that I want to give access to my account.

**Comment by ZakiChammaa** [comment]
If you changed the url for the redirect this will happen. It works
perfectly fine with me.

On Sat, Apr 2, 2016 at 3:27 PM, Justin Jean-Pierre <notifications@github.com

**Comment by justinjeanpierre** [comment]
I didn't change the redirect url (or anything else.)
